default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rivju_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

test:
  <<: *default
  database: rivju_test

production:
  <<: *default
  database: rivju_production
  username: rivju
  password: <%= ENV["RIVJU_DATABASE_PASSWORD"] %>
